name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # SETUP
      - uses: actions/checkout@v3
        with:
          repository: benjaminjonard/snibox-sqlite
          ref: main
          token: ${{ secrets.TEST_GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # DEPLOY
      - uses: docker/build-push-action@v4
        with:
          file: Dockerfile          
          push: true    
          tags: benjaminjonard/snibox
          platforms: linux/amd64,linux/arm64   
