name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # SETUP
      - uses: actions/checkout@v3
        with:
          repository: benjaminjonard/snibox-sqlite
          ref: config-improvements
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # DEPLOY
      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: prod
          push: true
          build-args: |
            VERSION=1.0.0
            BUILDHASH=12840d1bafd8373d38e589ae01ed1bdf037403a7
          tags: ${{ secrets.BETA_REPO_URL }}:snibox
